FROM node:22-alpine

WORKDIR /app

# Install dependencies
# This will be cached unless package.json changes
COPY package.json yarn.lock ./
RUN yarn install

# Source code will be mounted as volume
# So we don't copy it here for development

EXPOSE 3000

CMD ["npx", "nx", "serve", "crk-points-bank", "--host", "0.0.0.0"]
